import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import { useSwipeable } from "react-swipeable";
import { useRouter } from "next/router";

function SwipeableMain() {
  const router = useRouter();
  const handlers = useSwipeable({
    onSwipedRight: () => {
      router.push("/");
    },
  });
  return (
    <main {...handlers}>
      <div className="message">242342123</div>
      <div className="message">242342123</div>
      <div className="message message-me">242342123</div>
    </main>
  );
}

const Home: NextPage = () => {
  const [top, settop] = React.useState(5);

  const input = React.useRef<HTMLInputElement>(null);
  function onFocusInput() {
    if (navigator.userAgent.includes("iPhone")) {
      if (Number(localStorage.getItem("height"))) {
        settop(window.innerHeight - Number(localStorage.getItem("height")));
      }
    }
  }
  function onBlurInput() {
    if (navigator.userAgent.includes("iPhone")) {
      settop(5);
      localStorage.setItem("height", window.innerHeight.toString());
    }
  }
  function sendMessage(e: React.MouseEvent<HTMLButtonElement>) {
    input.current?.focus();
  }

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header black-container" style={{ top: `${top}px` }}>
        <Link href="/">
          <a className="header-button">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="27"
              height="24"
              fill="currentColor"
              viewBox="0 0 16 14"
            >
              <path
                fillRule="evenodd"
                d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"
              />
            </svg>
          </a>
        </Link>
        <span className="header-text">Name</span>
        <img src="" alt="" className="header-image" />
      </header>
      <SwipeableMain />
      <div className="black-container new-message">
        <input
          type="text"
          onFocus={onFocusInput}
          onBlur={onBlurInput}
          ref={input}
          placeholder="message..."
        />
        <button onClick={sendMessage}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="27"
            height="27"
            fill="currentColor"
            viewBox="0 0 16 16"
          >
            <path
              fillRule="evenodd"
              d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"
            />
          </svg>
        </button>
      </div>
    </div>
  );
};

export default Home;
